spring:
  application:
    name: user-center

eureka:
#  instance:
#     prefer-ip-address: true
#     ip-address: 127.0.0.1
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/